//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.19.0
//     from Assets/Script/Character/ChracterChangeControl.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Script/Character/ChracterChangeControl.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @CharacterChangeControl: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @CharacterChangeControl()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""ChracterChangeControl"",
    ""maps"": [
        {
            ""name"": ""CharacterChange"",
            ""id"": ""b5b37b74-2042-44b4-82c2-db8cf3527e36"",
            ""actions"": [
                {
                    ""name"": ""Change1"",
                    ""type"": ""Button"",
                    ""id"": ""3dd49a8e-5655-45fc-933a-552d0bf9b2ec"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Change2"",
                    ""type"": ""Button"",
                    ""id"": ""74136cd7-521f-4948-9f1c-c3e8a0b5fd03"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""10217db5-3126-40fd-af89-356c1cb89cc3"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Change1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3324d925-f486-4362-9f22-d60a9028ee3f"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Change2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // CharacterChange
        m_CharacterChange = asset.FindActionMap("CharacterChange", throwIfNotFound: true);
        m_CharacterChange_Change1 = m_CharacterChange.FindAction("Change1", throwIfNotFound: true);
        m_CharacterChange_Change2 = m_CharacterChange.FindAction("Change2", throwIfNotFound: true);
    }

    ~@CharacterChangeControl()
    {
        UnityEngine.Debug.Assert(!m_CharacterChange.enabled, "This will cause a leak and performance issues, CharacterChangeControl.CharacterChange.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CharacterChange
    private readonly InputActionMap m_CharacterChange;
    private List<ICharacterChangeActions> m_CharacterChangeActionsCallbackInterfaces = new List<ICharacterChangeActions>();
    private readonly InputAction m_CharacterChange_Change1;
    private readonly InputAction m_CharacterChange_Change2;
    /// <summary>
    /// Provides access to input actions defined in input action map "CharacterChange".
    /// </summary>
    public struct CharacterChangeActions
    {
        private @CharacterChangeControl m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public CharacterChangeActions(@CharacterChangeControl wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "CharacterChange/Change1".
        /// </summary>
        public InputAction @Change1 => m_Wrapper.m_CharacterChange_Change1;
        /// <summary>
        /// Provides access to the underlying input action "CharacterChange/Change2".
        /// </summary>
        public InputAction @Change2 => m_Wrapper.m_CharacterChange_Change2;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_CharacterChange; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="CharacterChangeActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(CharacterChangeActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="CharacterChangeActions" />
        public void AddCallbacks(ICharacterChangeActions instance)
        {
            if (instance == null || m_Wrapper.m_CharacterChangeActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CharacterChangeActionsCallbackInterfaces.Add(instance);
            @Change1.started += instance.OnChange1;
            @Change1.performed += instance.OnChange1;
            @Change1.canceled += instance.OnChange1;
            @Change2.started += instance.OnChange2;
            @Change2.performed += instance.OnChange2;
            @Change2.canceled += instance.OnChange2;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="CharacterChangeActions" />
        private void UnregisterCallbacks(ICharacterChangeActions instance)
        {
            @Change1.started -= instance.OnChange1;
            @Change1.performed -= instance.OnChange1;
            @Change1.canceled -= instance.OnChange1;
            @Change2.started -= instance.OnChange2;
            @Change2.performed -= instance.OnChange2;
            @Change2.canceled -= instance.OnChange2;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="CharacterChangeActions.UnregisterCallbacks(ICharacterChangeActions)" />.
        /// </summary>
        /// <seealso cref="CharacterChangeActions.UnregisterCallbacks(ICharacterChangeActions)" />
        public void RemoveCallbacks(ICharacterChangeActions instance)
        {
            if (m_Wrapper.m_CharacterChangeActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="CharacterChangeActions.AddCallbacks(ICharacterChangeActions)" />
        /// <seealso cref="CharacterChangeActions.RemoveCallbacks(ICharacterChangeActions)" />
        /// <seealso cref="CharacterChangeActions.UnregisterCallbacks(ICharacterChangeActions)" />
        public void SetCallbacks(ICharacterChangeActions instance)
        {
            foreach (var item in m_Wrapper.m_CharacterChangeActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CharacterChangeActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="CharacterChangeActions" /> instance referencing this action map.
    /// </summary>
    public CharacterChangeActions @CharacterChange => new CharacterChangeActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "CharacterChange" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="CharacterChangeActions.AddCallbacks(ICharacterChangeActions)" />
    /// <seealso cref="CharacterChangeActions.RemoveCallbacks(ICharacterChangeActions)" />
    public interface ICharacterChangeActions
    {
        /// <summary>
        /// Method invoked when associated input action "Change1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnChange1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Change2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnChange2(InputAction.CallbackContext context);
    }
}
